services:
  - type: web
    name: tradesmart-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.5
      - key: FLASK_APP
        value: src/app.py
      - key: FLASK_ENV
        value: production

  - type: web
    name: tradesmart-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: "./build"
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://tradesmart-backend.onrender.com


